### ISSUE TITLE
3.2 update

### ISSUE THREAD

**Issue by Legitti** [WilliamRagstad/Font-Manager#20]
I'm trying to download it from here: https://github.com/WilliamRagstad/Font-Manager/releases/download/v3.2/FontManager.exe

But its still 3.1 version and gives update notification about 3.2. Unable to update.

**Comment by ccsimplyspolit** [comment]
compiled from source
win 10 x64
http://www.mediafire.com/file/q01zb58gg1dd49x/CSGO_Font_manager_3.2.rar

**Comment by Legitti** [comment]
> compiled from source
> win 10 x64
> http://www.mediafire.com/file/q01zb58gg1dd49x/CSGO_Font_manager_3.2.rar

Didn't bother to change from 2.0 name? GL trying to get people open that.

**Comment by ccsimplyspolit** [comment]
i'm just compiled from source.


diff by release u can see here
https://github.com/WilliamRagstad/Font-Manager/compare/v3.2...release
and ye,  i given all files from compile, 
![image](https://user-images.githubusercontent.com/29892758/74036478-06d18200-49c5-11ea-85e8-936ae597dcaa.png)
but as says VS u need launch >  CSGO Font Manager.exe

**Comment by WilliamRagstad** [comment]
Do not open any other closed source version of Font Manager, for example, @ccsimplyspolit link is not to trust.
@Legitti You are correct, there is a problem which is fixed in this new version of Font Manager 3.3
