### ISSUE TITLE
Path Defaults to %HOMEPATH%\Documents\Font Manager

### ISSUE THREAD

**Issue by ioannedelea** [WilliamRagstad/Font-Manager#21]
So if you save the release executable, say on your Desktop, the program will throw a DirectoryNotFoundException. (as the "%HOMEPATH%\Documents\Font Manager" does not exist).

**Comment by Carl-Kabat** [comment]
same here

![Screenshot_1](https://user-images.githubusercontent.com/61113001/74605343-a67ac880-50c7-11ea-87bd-37781e977eee.png)

**Comment by WilliamRagstad** [comment]
Yes, this has been an issue for quite a while. Therefore I have chosen to move the Font Manager save location to%AppData% which will solve this problem.
