### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by rrroyal** [WilliamRagstad/Font-Manager#24]
Hiya! I would greatly appreciate if you credited me in readme as the person who have found the method to change fonts 😄

**Comment by WilliamRagstad** [comment]
Hi! sorry, who are you? I can’t credit anyone without knowing that they actually are in the rightful position of being credited you see.

You doesn’t seem to have any work on this topic on your Github, nor your linked website.
Therefore I’ll need some other indication that you in fact have come up with this unique method of font replacement.

My only source when building this program was a video produced by BananaGaming, and unless he doesn’t tell me that he got his information from you, I sadly cannot credit you for contributing to this project.

**Comment by rrroyal** [comment]
Maxim have updated the [video description](https://www.youtube.com/watch?v=4p8QVfk7ltQ) confirming that I am the one who I claim to be

**Comment by WilliamRagstad** [comment]
Great! Thanks, credits have been added.
