### ISSUE TITLE
Downloaded the new release but it does not want to update

### ISSUE THREAD

**Issue by Adenis890** [WilliamRagstad/Font-Manager#27]
I downloaded the latest release but for some reason it keeps giving me this error. I tried to reinstall it, deleted the appdata folder and still nothing. It keeps telling me that a new version 3.4 is out and if i want to install it, i click yes and this happens (i will put the screenshots). If i press no it's just gonna use the 3.3 version.
![image](https://user-images.githubusercontent.com/52959977/78220508-59618300-74ca-11ea-9eed-adc6f64235f4.png)
![image](https://user-images.githubusercontent.com/52959977/78220537-6a11f900-74ca-11ea-908c-00ef213d8be4.png)

**Comment by Lukaps4** [comment]
same here

**Comment by WilliamRagstad** [comment]
Interesting...

Have you made sure that the folder has not restrictive file privileges? Right click on the parent folder and look under Security, there you might be able to see any user/group access privileges which you can modify.

Otherwise, try placing the `FontManager.exe` file in another location on your computer where you are sure any process can access. The problem might originate in the fact that you currently have Font Manager stored in some external USB drive, or similar (?). Try to move the `.exe` file to a location in `C:\` or similar hard drive.

**Comment by Adenis890** [comment]
> Interesting...
> 
> Have you made sure that the folder has not restrictive file privileges? Right click on the parent folder and look under Security, there you might be able to see any user/group access privileges which you can modify.
> 
> Otherwise, try placing the `FontManager.exe` file in another location on your computer where you are sure any process can access. The problem might originate in the fact that you currently have Font Manager stored in some external USB drive, or similar (?). Try to move the `.exe` file to a location in `C:\` or similar hard drive.


Modified permissions and still the same thing is happening and also i don't have it on a external hard drive. Tried moving it and nothing.

**Comment by marto05** [comment]
Same problem

**Comment by WilliamRagstad** [comment]
Could you provide more information about where you have your `FontManager.exe` file?
Does the updater.exe file exist in `C:\Users\super\AppData\Roaming\Font Manager\Data\updater.exe`?

**Comment by Adenis890** [comment]
> Could you provide more information about where you have your `FontManager.exe` file?
> Does the updater.exe file exist in `C:\Users\super\AppData\Roaming\Font Manager\Data\updater.exe`?

The  .exe file is in a folder in the B: partition. The updater.exe file is in appdata.

**Comment by WilliamRagstad** [comment]
What type is the B: partition? Internal harddrive?
Is the `Font Manager` folder in `AppData` protected in some way?

**Comment by Legitti** [comment]
Same problem. Even downloaded the new exe but still says 3.3

**Comment by Davidovsky666** [comment]
Same as above. +Tried some things like redownloading etc. or moving to other drives but still the update doesn't work. Can't even turn the message about the update off, it always comes up on program start and wants me to update even tho I downloaded the latest available release after I failed to update from 3.3.

**Comment by encryptics** [comment]
> I downloaded the latest release but for some reason it keeps giving me this error. I tried to reinstall it, deleted the appdata folder and still nothing. It keeps telling me that a new version 3.4 is out and if i want to install it, i click yes and this happens (i will put the screenshots). If i press no it's just gonna use the 3.3 version.
> ![image](https://user-images.githubusercontent.com/52959977/78220508-59618300-74ca-11ea-9eed-adc6f64235f4.png)
> ![image](https://user-images.githubusercontent.com/52959977/78220537-6a11f900-74ca-11ea-908c-00ef213d8be4.png)

**Comment by encryptics** [comment]
Go to the release type of download, do the download thing blah blah blah, when it asks to update just press no and your set, at least that's how I did it.

**Comment by encryptics** [comment]
Found another way to do it, https://github.com/WilliamRagstad/Font-Manager/tree/v3.4 just have to download 3.4, press no on update, your set, works perfectly.

**Comment by ngutierrez71** [comment]
Is this problem fixed? I have the same problem

**Comment by sideskroll** [comment]
Having the same exact error pop up and NOT updating seems to be the only way to get the app to work for now.
By the way, some fonts dont display correctly IN the app (making it difficult to adjust font size) even though they do work in CS.
If you'd like to take a look at the issue you could try the "MachineScript" font (either regular or standard)
Regular: https://fontzone.net/font-download/machinescript-regular
Standard: https://dl.dafont.com/dl/?f=machine_script
Thanks for the work youve put into this app. It sure as hell simplifies something Valve should give us access to change by default.
Thanks,

**Comment by WilliamRagstad** [comment]
There was a small piece of the code that needed updating, which should have been noticed long before this happened. The problem discussed here should have been fixed now and re-downloading the latest client will fix the problem. As you might have already noticed, all clients that was released in 3.4 somehow got the wrong version number. This is fixed now, try updating as normal and leave a comment here if anything goes wrong or tell me if it works for you.

**Comment by Legitti** [comment]
Thanks, just tried it and now it works!
