### ISSUE TITLE
I installed it fine... but now there isnt a star next to my knife.

### ISSUE THREAD

**Issue by OblivionCSGO** [WilliamRagstad/Font-Manager#28]
Do you know why there isn't a star next to my knife?

**Comment by OblivionCSGO** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/63506514/79046955-6de40080-7bd9-11ea-940c-ad205a218f0a.png)

**Comment by WilliamRagstad** [comment]
That’s because the Font you are using does not support that Unicode character, often you can preview fonts before downloading them.
