### ISSUE TITLE
Opening the software?

### ISSUE THREAD

**Issue by nF-V1bEz** [WilliamRagstad/Font-Manager#30]
Whenever i install the folder, i extract it but nowhere to i find a way to open the manager, i've used this before and its worked perfectly but now it doesn't allow me to actually open the program

**Comment by FarmerFinn** [comment]
Same with me and I cant find the exe font manager

**Comment by WilliamRagstad** [comment]
Hello @nF-V1bEz, could you be more specific? Which folder are you talking about, and how does it not allow you to open the program?

**Comment by Ksh-man** [comment]
@WilliamRagstad I may just be a fool for not being able to find the .exe file, but after v3.3(i.e v3.4 and v3.5), there is no BIN folder. There are no .exe files whatsoever.

**Comment by WilliamRagstad** [comment]
As @ksh-man said, there is no need for downloading the whole repository, if you’re looking for the FontManager.exe file, there is a download to the latest release on the main page.

**Comment by BugFlxer** [comment]
https://github.com/WilliamRagstad/Font-Manager/releases
Choose The Latest Version Just Like Dutch said
