### ISSUE TITLE
Font Will Not Change

### ISSUE THREAD

**Issue by ernest290** [WilliamRagstad/Font-Manager#38]
Whenever I try to change my font to anything it simply doesn't change.
I select my font.
Press "Apply Selected Font".
And get prompted with "Successfully Applied {font name}".
I open CsGo and it's just the regular font.
One thing I did notice is when I open CsGo after changing my font, before saying "Launching Counter Strike Global Offensive" it says "Updating Configuration".

**Comment by ernest290** [comment]
I solved this manually by going to `AppData`, going into my font folder, coping the font.conf and placing it in the CsGo fonts folder.

**Comment by M1XT3NZ** [comment]
Did you have 2 csgo folders?
The font manager probably got the wrong folder.
If you would click on "reset"
you could see which folder it takes.

Same happened to me :)
