### ISSUE TITLE
I reinstalled as it wasnt working and when i tried to open the .exe again it denied me access and deleted itself

### ISSUE THREAD

**Issue by Orsina1** [WilliamRagstad/Font-Manager#40]

**Comment by Orsina1** [comment]
It did

**Comment by Orsina1** [comment]
It did

Στις Σάβ, 12 Δεκ 2020 στις 11:00 μ.μ., ο/η M1XT3NZ <notifications@github.com>
έγραψε:

**Comment by WilliamRagstad** [comment]
Add font manager to the allowed programs list in Windows defender. If that doesn't work please provide detailed information of the steps you're taking here.

**Comment by Orsina1** [comment]
oh i fixed it by redownloading it a long time ago

Στις Τρί, 5 Ιαν 2021 στις 4:51 μ.μ., ο/η William Rågstad <
notifications@github.com> έγραψε:
